packages:
  - apps/*
  - packages/*
onlyBuiltDependencies:
  - '@discordjs/opus'
  - bufferutil
  - erlpack
  - zlib-sync
publicHoistPattern:
  - '*bufferutil*'
  - '*erlpack*'
  - '*fzstd*'
  - '*zlib-sync*'
