packages:
  - apps/*
  - packages/*
  - scripts
onlyBuiltDependencies:
  - bufferutil
  - erlpack
  - sharp
  - zlib-sync
publicHoistPattern:
  - '*bufferutil*'
  - '*erlpack*'
  - '*fzstd*'
  - '*sharp*'
  - '*zlib-sync*'
