export const REQUEST_CONSTANTS = {
  MIN_RETRY_DELAY: 100,
  MAX_JITTER: 500,
  NON_RETRYABLE_STATUS_CODES: [401, 403, 404],
  NETWORK_ERROR_PATTERNS: [
    "ECONNRESET",
    "ETIMEDOUT",
    "ECONNREFUSED",
    "EPIPE",
    "ENOTFOUND",
    "ENETUNREACH",
  ],
} as const;

export type RequestConstants =
  (typeof REQUEST_CONSTANTS)[keyof typeof REQUEST_CONSTANTS];
