/**
 * Enum representing various MIME types.
 *
 * @see {@link https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types|MIME types}
 */
export enum MimeTypes {
    Aac = "audio/aac",
    Abw = "application/x-abiword",
    Avi = "video/x-msvideo",
    Azw = "application/vnd.amazon.ebook",
    Bin = "application/octet-stream",
    Bmp = "image/bmp",
    Bz = "application/x-bzip",
    Bz2 = "application/x-bzip2",
    Csh = "application/x-csh",
    Css = "text/css",
    Csv = "text/csv",
    Doc = "application/msword",
    Docx = "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    Eot = "application/vnd.ms-fontobject",
    Epub = "application/epub+zip",
    Gif = "image/gif",
    Html = "text/html",
    Ico = "image/x-icon",
    Ics = "text/calendar",
    Jar = "application/java-archive",
    Jpeg = "image/jpeg",
    Js = "application/javascript",
    Json = "application/json",
    Midi = "audio/midi",
    Mpeg = "video/mpeg",
    Mpkg = "application/vnd.apple.installer+xml",
    Odp = "application/vnd.oasis.opendocument.presentation",
    Ods = "application/vnd.oasis.opendocument.spreadsheet",
    Odt = "application/vnd.oasis.opendocument.text",
    Oga = "audio/ogg",
    Ogv = "video/ogg",
    Ogx = "application/ogg",
    Otf = "font/otf",
    Pdf = "application/pdf",
    Png = "image/png",
    Ppt = "application/vnd.ms-powerpoint",
    Pptx = "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    Rar = "application/x-rar-compressed",
    Rtf = "application/rtf",
    Sh = "application/x-sh",
    Svg = "image/svg+xml",
    Swf = "application/x-shockwave-flash",
    Tar = "application/x-tar",
    Tiff = "image/tiff",
    Ts = "application/typescript",
    Ttf = "font/ttf",
    Vsd = "application/vnd.visio",
    Wav = "audio/x-wav",
    Weba = "audio/webm",
    Webm = "video/webm",
    Webp = "image/webp",
    Woff = "font/woff",
    Woff2 = "font/woff2",
    Xhtml = "application/xhtml+xml",
    Xls = "application/vnd.ms-excel",
    Xlsx = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    Xml = "application/xml",
    Xul = "application/vnd.mozilla.xul+xml",
    Zip = "application/zip",
    _3g2 = "video/3gpp2",
    _3gp = "video/3gpp",
    _7z = "application/x-7z-compressed",
}
